server:
  port: 9000
#  servlet:
#    context-path: /

#spring.cloud.config.server.git.uri: https://github.com/forezp/SpringcloudConfig/
#spring.cloud.config.server.git.searchPaths: respo
#spring.cloud.config.label: master
#spring.cloud.config.server.git.username:
#spring.cloud.config.server.git.password:

eureka:
  instance:
#    hostname: 172.17.0.1
    hostname: localhost
    instance-id: ${server.port}
  client:
    #register-with-eureka: false  #不要向注册中心注册自己
    #fetch-registry: false  #禁止检索服务
    serviceUrl.defaultZone: http://${eureka.instance.hostname}:8000/eureka/

logging:
  path: classpath:logback.xml

spring:
  application:
    name: config-server
  cloud:
    config:
      label: master
      server:
        git:
          uri: https://github.com/independenter/spring-cloud-config/
          search-paths: config
#          username: independenter
#          password: #####
